[package]
name = "zellij-shortcutbar"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zellij-tile = "0.39.0"
ansi_term = "0.12.1"
chrono = "0.4.0"
